#!/bin/bash

# $1 = volumegroup
# $2 = size
# #3 = count

if [[ -z ${stripsize+x} ]]; then
   stripsize=8
   fi

if [ $# -eq 0 ]; then
   echo "pvcreatelun volgroup size count"
   echo "    volgroup is the volgroup as created by vgcreate"
   echo "    size - example 1G"
   echo "    count - Optional - Number of luns to create"
   echo " $OSEUSERNAME should be set to the Openshift User Name"
   exit 0
   fi
# Call ourselves recursively to do repeats
if [ $# -eq 3 ]; then
   for ((i=0;i < $3;i++))
       do
      ./ose_pvcreate_lun $1 $2
      done
    exit 0
   fi

STOREIP=$(hostname --ip-address)
LUNFILE=~/.oseluncount.cnt
DEVFILE=~/.osedevcount.cnt
TAG=$0

if [ -e ${LUNFILE} ]; then
    count=$(cat ${LUNFILE})
else
    touch "$LUNFILE"
    count=0
fi

if [ -e ${DEVFILE} ]; then
    dcount=$(cat ${DEVFILE})
else
    touch "$DEVFILE"
    dcount=1
   echo ${dcount} > ${DEVFILE}
fi

lunid=${count}
((count++))

echo ${count} > ${LUNFILE}

export volname=ose"$count"x"$2"
printf -v padcnt "%03d" $count
export padcnt

lvcreate -L $2 -i$stripsize -I64 -n $volname $1 | logger --tag $TAG
mkfs.ext4 -q -F _F /dev/vg1/$volname 2>&1 | logger --tag $TAG
if [ ${count} -eq 1 ]; then
     echo "Setup device"
     targetcli /iscsi create iqn.2016-02.local.store${dcount}:t1 |  logger --tag $TAG
     targetcli /iscsi/iqn.2016-02.local.store${dcount}:t1/tpg1/acls create iqn.2016-02.local.azure.nodes | logger --tag $TAG
     targetcli /iscsi/iqn.2016-02.local.store${dcount}:t1/tpg1/ set attribute authentication=0 | logger --tag $TAG
     targetcli saveconfig
fi

targetcli backstores/block/ create "$volname" /dev/vg1/"$volname" |  logger --tag $TAG
targetcli /iscsi/iqn.2016-02.local.store${dcount}:t1/tpg1/luns create /backstores/block/"$volname" | logger --tag $TAG

targetcli saveconfig | logger --tag $TAG

cat <<EOF > $volname.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsipv${dcount}x${padcnt}
spec:
  capacity:
    storage: ${2}Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: $STOREIP
     iqn: iqn.2016-02.local.store${dcount}:t1
     lun: ${lunid}
     fsType: 'ext4'
     readOnly: false

EOF
oc create -f $volname.yml
rm -f $volname.yml
if [ ${count} -eq 100 ]; then
   ((dcount++))
   count=0
   echo ${count} > ${LUNFILE}
   echo ${dcount} > ${DEVFILE}
fi

