#!/bin/bash

# $1 = volumegroup
# $2 = size
# #3 = count

if [ $# -eq 0 ]; then
   echo "pvcreatelun volgroup size count"
   echo "    volgroup is the volgroup as created by vgcreate"
   echo "    size - example 1G"
   echo "    count - Optional - Number of luns to create"
   exit 0
   fi
# Call ourselves recursively to do repeats
if [ $# -eq 3 ]; then
   for ((i=0;i < $3;i++))
       do
      ./ose_pvcreate_lun $1 $2
      done
    exit 0
   fi

LUNFILE=~/.oseluncount.cnt
TAG=$0

if [ -e ${LUNFILE} ]; then
    count=$(cat ${LUNFILE})
else
     targetcli /iscsi create iqn.2016-02.local.store1 | logger --tag $TAG
     targetcli /iscsi/iqn.2016-02.local.store1/tpg1/acls create iqn.2016-02.local.azure.nodes | logger --tag $TAG
     targetcli /iscsi/iqn.2016-02.local.store1/tpg1/ set attribute authentication=0 | logger --tag $TAG
    touch "$LUNFILE"
    count=0
fi

((count++))

echo ${count} > ${LUNFILE}

export volname=vol"$count"x"$2"

lvcreate -L $2 -n $volname $1 | logger --tag $TAG
mkfs.ext4 /dev/vg1/$volname 2>&1 | logger --tag $TAG
targetcli backstores/block/ create "$volname"_server /dev/vg1/"$volname" | logger
targetcli /iscsi/iqn.2016-02.local.store1/tpg1/luns create /backstores/block/"$volname"_server | logger --tag $TAG
targetcli saveconfig | logger --tag $TAG


