apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 172.16.55.177
     iqn: iqn.nonsense
     lun: 0
     fsType: 'ext4'
     readOnly: false
